### ISSUE TITLE
Issue with Redirect

### ISSUE THREAD

**Issue by TorbenHammes** [Muljin/msal-flutter#13]
Hey there,
I'm at a loss as to what to do. I want to integrate Azure AD B2C with my Flutter app, have the correct authority, client ID and separate redirect URIs for IOS and Android respectively as shown to me in Azure in the registered app to the tenant under authentication. 

In the Info.plist I have the following:
```
<key>CFBundleURLTypes</key>
    <array>
        <dict>
            <key>CFBundleURLSchemes</key>
            <array>
                <string>msauth.<my.identifier.app></string>
            </array>
        </dict>
    </array>
    <key>LSApplicationQueriesSchemes</key>
    <array>
    	<string>msauthv2</string>
    	<string>msauthv3</string>
    </array>
```

My AppDelegate.swift file looks like this:
```swift
import UIKit
import Flutter
import MSAL

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
  override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
  guard let sourceApplication = options[UIApplication.OpenURLOptionsKey.sourceApplication] as? String else {
      return false
  }
  return MSALPublicClientApplication.handleMSALResponse(url, sourceApplication: sourceApplication)
  }
}
```
As described in the instructions, I added this.

The redirects are the same in the documents as they are online in the ten

ant in the registered app.

What can I do. 
Attached is a video of what it currently looks like on my end.
https://user-images.githubusercontent.com/12980389/197001789-481ed276-6c58-4952-9b02-ccf34543a7ef.mp4

Thanks in advance and best regards from Berlin
Torben

**Comment by mswehli** [comment]
Sorry but due to our limited resources we cannot offer support. If you find a bug and know the steps to solve it please let us know, however we have an update to the library in the works which we'll be releasing soon.
