### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by emaborsa** [Muljin/msal-flutter#20]
Hi all,

I already have a flutter project, trying to add msal_flutter:

```
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.7.21 and higher.
The following dependencies do not satisfy the required version:
project ':msal_flutter' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.31

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Exception: Gradle task assembleDebug failed with exit code 1
```

Can I fix it in the gradle files or is it a library problem?

**Comment by vasantikaHorizontal** [comment]
Hi @emaborsa Have you found any solution? I am facing the same issue in my project. Please help me if you found any solution. Thanks in advance.

**Comment by emaborsa** [comment]
Hi,
I must say, I discarded the library. It is not maintened and no support at all.

**Comment by vasantikaHorizontal** [comment]
Okay Thank you for your response. Can you suggest me any library for MSAL which is maintained properly?

**Comment by emaborsa** [comment]
Unfortunately there are no libraries yet. I was thinking about to write by my self just what I need.

**Comment by vasantikaHorizontal** [comment]
Okay, Thanks!

**Comment by mswehli** [comment]
Sorry but we have no capacity to support. This plugin is provided as is as we use it internally and share it if anyone finds it interesting, however we're happy for anyone to fork and improve it.
In regards to the error you see however, I would suggest first trying to just edit the kotlin plugin version directly from the package local cache which might work, or lowering your own kotlin version. If you do come up with a solution please feel free to create a pull request so others may benefit from it.
