### ISSUE TITLE
MSAL doesn't work in release mode

### ISSUE THREAD

**Issue by Mon-ira** [Muljin/msal-flutter#32]
I successfully integrated MSAL package in my project and it works fine in debug mode I can acquire token and everything is fine except when I run my app in release mode the package throughs an exception 
[+9615 ms] I/flutter (16886): called acquiretoken
[        ] I/flutter (16886): creating pca...
[        ] I/flutter (16886): authorities
[        ] I/flutter (16886): browser_safelist
[ +185 ms] E/flutter (16886): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Instance of 'MsalException'
[        ] E/flutter (16886): #0      MSALPublicClientApplication._initialize (package:msal_flutter/src/msal_public_client_application.dart:28)
msal_public_client_application.dart:1
[        ] E/flutter (16886): <asynchronous suspension>
[   +1 ms] E/flutter (16886): #1      MSALPublicClientApplication.createPublicClientApplication

**Comment by Mon-ira** [comment]
Found A mistake in my configurations

**Comment by ngocbaomobile** [comment]
@Mon-ira  I have issue on release two, but i work on debug
